### ISSUE TITLE
provide sources for GPL-externals

### ISSUE THREAD

**Issue by umlaeute** [iceblinkdigital/GemmaLib#1]
some of the externals you are bundling with GemmaLib are released under the GNU General Public License and require *you* to distribute the sources along with any binaries.

however, i cannot locate any sources in todays master.

**Comment by iceblinkdigital** [comment]
Hi, thanks for notifying me the issue.

I will add the C code source files for the GPL based externals. Can it be
located in the different folder but in the same repository?

Thank you.

Best wishes
Zack

2016-02-28 21:00 GMT+01:00 umläute <notifications@github.com>:

**Comment by umlaeute** [comment]
they can be in any directory.
actually, they don't even need to be in the same *repository*, it's just your responsibility to make the sources available to any user of your binary data. (putting them into the repository might be the easiest way).

alternatively you might use `git submodules` to reference any git-managed externals.
(though if the upstream git repositories disappear, you still need to be able to provide the sources somehow).

**Comment by iceblinkdigital** [comment]
I created a new repository that has all the external source codes. Thank you!
