### ISSUE TITLE
name containing version number?

### ISSUE THREAD

**Issue by umlaeute** [iceblinkdigital/GemmaLib#2]
do you plan to create a new repository or each release of GemmaLib?

wouldn't it make more sense to have a single repository `https://github.com/iceblinkdigital/GemmaLib` and create tags for the versions? (on your homepage you would then link directly to the tags, e.g. https://github.com/iceblinkdigital/GemmaLib/tags/v1.0.1)

**Comment by iceblinkdigital** [comment]
Thank you I will try to fix that.

Should I delete the previous repository and recreate one then? Or could you
fix that for me if possible?

I'm sorry I'm not really used to using the Github yet.

I appreciate your support.

Best regards,
Zack

2016-02-28 21:02 GMT+01:00 umläute <notifications@github.com>:

**Comment by umlaeute** [comment]
just going to your [project settings](https://github.com/iceblinkdigital/GemmaLib-1.0.1/settings) and renaming the repository should be enough.

iirc, github will keep the old URL valid, so you don't have to worry too much about broken links.

**Comment by iceblinkdigital** [comment]
Thank you so much for your help!!

Best wishes,
Zack

2016-02-29 20:53 GMT+01:00 umläute <notifications@github.com>:

**Comment by umlaeute** [comment]
thanks for renaming
